
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_flyflix
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flyflix
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flyflix-network

volumes:
  mysql_data:

networks:
  flyflix-network:
    driver: bridge
